version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/ui'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      angular:
        applies-to: version-updates
        patterns:
          - '@angular*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: '@angular*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'gradle'
    directory: '/server'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
